-- GoStay HMS — Decouple identity from Supabase Auth
--
-- Identity now comes from Ventera SSO, not Supabase Auth. Two things in
-- 001_initial_schema.sql assumed otherwise and made it impossible to create a
-- profile at all:
--
--   1. profiles.id had a foreign key to auth.users(id). Since nothing ever
--      writes to auth.users now, that FK rejected every insert.
--   2. on_auth_user_created fired off auth.users to create the profile row.
--      That trigger can never fire, so profiles stayed empty — which in turn
--      made get_my_role() return NULL and every RLS policy evaluate false.
--
-- The JWT that the app presents is minted by api/sso/token.ts and carries
-- `sub` = uuid_v5(SSO_UUID_NAMESPACE, sso_sub), so auth.uid() keeps working
-- unchanged and none of the policies in 002 need rewriting.

-- ─── 1. Remove the auth.users trigger ────────────────────────────────────────
drop trigger if exists on_auth_user_created on auth.users;
drop function if exists handle_new_user();

-- ─── 2. Detach profiles.id from auth.users ───────────────────────────────────
-- The constraint name is generated by Postgres; find it rather than guess.
do $$
declare
  fk_name text;
begin
  select con.conname into fk_name
  from pg_constraint con
  join pg_class rel on rel.oid = con.conrelid
  join pg_namespace nsp on nsp.oid = rel.relnamespace
  where rel.relname = 'profiles'
    and nsp.nspname = 'public'
    and con.contype = 'f'
    and con.conkey = array[
      (select attnum from pg_attribute
        where attrelid = rel.oid and attname = 'id')
    ];

  if fk_name is not null then
    execute format('alter table public.profiles drop constraint %I', fk_name);
  end if;
end $$;

-- ─── 3. Record the SSO subject the id was derived from ───────────────────────
-- profiles.id stays a uuid so auth.uid() comparisons work untouched; sso_sub
-- keeps the original opaque claim for traceability and lookup.
alter table profiles add column if not exists sso_sub text;

create unique index if not exists profiles_sso_sub_key
  on profiles (sso_sub)
  where sso_sub is not null;

comment on column profiles.sso_sub is
  'Ventera SSO subject claim. profiles.id = uuid_v5(namespace, sso_sub), minted by api/sso/token.ts.';

-- ─── 4. Let a profile exist before the user has any bookings ─────────────────
-- "Users can view own profile" (002) is enough for a signed-in user to read
-- their own row, but nothing allowed the row to be created. Provisioning runs
-- server-side with the service_role key, which bypasses RLS, so no INSERT
-- policy is added here on purpose — profiles must not be self-insertable.
